name: PR ìš”ì²­ Slack ì „ì†¡

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: send pr to slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.CODE_REVIEW_SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: "github_frontend"
          SLACK_USERNAME: "Monolith_ì½”ë“œë¦¬ë·°_ìš”ì²­"
          SLACK_ICON: ":kakaostyle"
          SLACK_COLOR: "good"
          SLACK_MESSAGE: "ë¦¬ë·° í•œë²ˆë§Œ ë¶€íƒë“œë¦½ë‹ˆë‹¤. ğŸ™\n<${{ github.event.pull_request.html_url }}|PR í™•ì¸í•˜ê¸°>"
          SLACK_FOOTER: ""
          MSG_MINIMAL: "true"
